config/routes.rb
Rails.application.routes.draw do
  # HACK: registrationsコントローラのcancelとdestroyは利用していない
  devise_for :user, only: %i[sessions registrations]

  # except より only 使ったほうが安全
  # resources :tweets, except: %i[edit update index] do
  resources :tweets, only: %i[show new create destroy] do
    # show => like 一覧ページ
    member do
      post :like
      delete :unlike
    end

    # index => いいねした人リスト
    # create => いいね
    # destroy => いいね取り下げ
    resources :likes, only: %i[index create destroy]

    resources :comments, only: %i[index create destroy]
  end

  resources :users, only: :show do
    member do
      post :follow
      delete :unfollow
    end
  end

  namespace :users do
    resources :tweets, only: %i[destroy]
    # def set_tweet
    #   @tweet = current_user.tweets.find(params[:id])
    # end
  end

  namespace :admins do
    resources :tweets
  end

  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :body, presence: true, length: { maximum: 140 }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follow_user, class_name: 'User', foreign_key: 'follow_user_id'
  belongs_to :follower, class_name: 'User', foreign_key: 'follower_id'
  validates :follow_user_id, uniqueness: { scope: :follower_id }
  validate :cannot_follow_myself

  def cannot_follow_myself
    return unless follower_id == follow_user_id

    errors.add(:follow_user_id, 'は自分以外のユーザーを指定してください')
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :tweet_id, uniqueness: { scope: :user_id }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

  validates :body, presence: true, length: { maximum: 140 }

  # 違うクラスを作る
  # SQL の Window 関数を使うとランクの番号振りが楽できそう
  # モデルに書いてあるのは good
  def self.yesterday_likes_ranking_top(limit)
    likes_count = Like.where(created_at: Date.yesterday...Date.today)
                      .group(:tweet_id)
                      .order('COUNT(tweet_id) DESC')
                      .count
    rank = 1
    result = []
    likes_count.each.with_index(1) do |(tweet_id, count), index|
      rank = index if result.present? && result.last[:count] > count
      break if rank > limit

      result.push({ tweet: Tweet.find(tweet_id), rank: rank, count: count })
    end
    result
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, authentication_keys: [:name]

  has_many :tweets, dependent: :destroy
  has_many :follows, class_name: 'Follow', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Follow', foreign_key: 'follow_user_id', dependent: :destroy
  has_many :follow_users, through: :follows, source: :follow_user
  has_many :follow_users_tweets, through: :follow_users, source: :tweets
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true,
                   uniqueness: true,
                   length: { maximum: 20 },
                   format: { with: /\A[a-zA-Z]+\z/, allow_blank: true }
  validates :profile, length: { maximum: 200 }

  def following?(user)
    # follow_users.exists?(follow_user: user)
    follow_users.pluck(:follow_user_id).include?(user.id)
  end

  def like_tweet?(tweet_id)
    # likes.exists?(tweet_id: tweet_id)
    likes.pluck(:tweet_id).include?(tweet_id)
  end
end

app/controllers/admins/application_controller.rb
class Admins::ApplicationController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_admin!
end

app/controllers/admins/tweets_controller.rb
class Admins::TweetsController < Admins::ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: %i[email]
    devise_parameter_sanitizer.permit :account_update, keys: %i[profile blog_url]
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == Rails.application.credentials.basic[:username] && password == Rails.application.credentials.basic[:password]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet
  before_action :set_comments, only: %i[index create]

  def index
    @comments = @tweet.comments.includes(:user)
  end

  def create
    @comment = @tweet.comments.build(comment_params)
    # 具体的なデータの設定はこちらで
    # @comment.user = current_user
    if @comment.save
      # deliver => deliver_now, deliver_later
      CommentMailer.new_comment(@comment).deliver
      # この redirect は turbolinks が拾ってくれている
      # html 以外のときは respond_to { |format| ... } を使うと特殊感が伝わる
      redirect_to root_url, notice: 'コメントを送りました。'
    else
      # index と create の view を分けると @comments のロードが不要になる
      # create では form 部分だけを置き換える
      render :index
    end
  end

  def destroy
    # アクション分けたほうがよさそう
    comment = current_user.comments.find(params[:id])
    # destroy!
    comment.destroy
    redirect_to root_url, notice: 'コメントを削除しました。'
  end

  private

    def set_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end

    def set_comments
      @comments = @tweet.comments.includes(:user)
    end

    def comment_params
      # ここは strong parameter で項目を絞るのが目的の場所なので具体的なデータは含めない
      params.require(:comment).permit(:body).merge(user: current_user)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # ApplicationController で before_action して、必要に応じて skip_before_action するほうが安全
  before_action :authenticate_user!
  before_action :set_tweet, only: %i[show like unlike]

  def index
    # created_at に index つけたほうがよさそう
    # pagination をつけたほうがよさそう
    # includes つけてるの good
    # .all 不要
    @tweets = Tweet.all.order(created_at: 'DESC').includes(:user, :likes)
    # ページとして分けたほうがシステムには優しそう
    @follow_users_tweets = current_user.follow_users_tweets.order(created_at: 'DESC').includes(:user, :likes)
  end

  def show; end

  # scaffold みたいで読みやすい
  def new
    @tweet = current_user.tweets.build
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      redirect_to root_url, notice: 'つぶやきを投稿しました。'
    else
      render :new
    end
  end

  def destroy
    # リソースの引き方の違いをアクションで吸収することはあまりしない。routing 分けるのがよさそう
    tweet = current_user.tweets.find(params[:id])
    tweet.destroy
    redirect_to root_url, notice: 'つぶやきを削除しました。'
  end

  def like
    # find_or_create_by 使わないと多重に作ろうとしてエラーになりそう
    # @tweet.likes.find_or_create_by(user: current_user)
    @tweet.likes.create(user_id: current_user.id)
  end

  def unlike
    # destroy! を使ってエラーを無視しないようにする
    # @tweet.likes.find_by(user_id: current_user.id)&.destroy!
    @tweet.likes.find_by(user_id: current_user.id).try(:destroy)
    render :like
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:body, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show follow unfollow]

  def show; end

  def follow
    current_user.follows.create(follow_user_id: @user.id)
    redirect_to root_url, notice: "#{@user.name} をフォローしました。"
  end

  def unfollow
    current_user.follows.find_by(follow_user_id: @user.id).try(:destroy)
    redirect_to root_url, notice: "#{@user.name} のフォローを解除しました。"
  end

  private

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.haml
= simple_form_for comment, url: tweet_comments_path(comment.tweet), wrapper: :inline_form, remote: true, id: 'hgoehoge' do |f|
  .form-row
    .col-10
      = f.input :body, placeholder: 'コメントを送る'
    .col-auto
      = f.button :submit, '送信', class: 'btn-outline-primary'

app/views/comments/_index.html.haml
.modal#comments{tabindex: '-1', role: 'dialog'}
  .modal-dialog.modal-dialog-centered{role: 'document'}
    .modal-content
      .modal-header
        %h5.modal-title コメント
      .modal-body.p-0
        %ul.list-group.list-group-flush
          - comments.each do |comment|
            %li.list-group-item
              %h5
                .row
                  .col-auto.mr-auto= link_to comment.user.name, comment.user, onclick: "$('.modal').modal('hide');"
                  .col-auto
                    - if comment.user == current_user
                      = link_to '削除', tweet_comment_path(comment.tweet, comment), method: :delete, class: 'btn btn-sm btn-outline-danger', data: { confirm: '削除してもいいですか？' }
              %p= raw h(comment.body).gsub(/\R/, '<br>')
              %p
                %small.text-muted
                  = comment.created_at.strftime('%Y/%m/%d %H:%M')
          %li.list-group-item#hogehoge
            = render 'form', comment: comment
      .modal-footer
        %button.btn.btn-secondary{type: 'button', data: {dismiss: 'modal'}} 閉じる

app/views/comments/create.js.erb
$('#hogehoge').html('<%= j(render 'form', comment: @comment) %>')

app/views/comments/index.js.erb
$("#comments").modal('hide');
$("#comments").replaceWith("<%= escape_javascript(render partial: 'index', locals: {comments: @comments, comment: @tweet.comments.build}) %>");
$("#comments").modal('show');
$("#comments").scrollTop($("form").offset().top);

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ミニブログ2
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body{style: 'padding-top: 5rem;'}
    - if user_signed_in?
      %nav.navbar.navbar-expand.navbar-dark.fixed-top.bg-dark
        .container
          = link_to 'ミニブログ', root_path, class: 'navbar-brand'
          .collapse.navbar-collapse
            %ul.navbar-nav.ml-auto
              %li.nav-item.dropdown
                %a#usermenu.nav-link.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}, aria: {haspopup: true, expanded: false}} メニュー
                .dropdown-menu.dropdown-menu-right{aria: {labelledby: 'usermenu'}}
                  = link_to 'アカウント設定', edit_user_registration_path, class: 'dropdown-item'
                  = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'dropdown-item'
    .container
      .row
        .col
          - flash.each do |key, value|
            - type = key == 'notice' ? 'info' : 'danger'
            %div{class: "alert alert-#{type}"}
              = value
              %button.close{type: 'button', data: {dismiss: 'alert'}, aria: {label: 'Close'}}
                %span{aria: {hidden: 'true'}} &times;
          = yield

app/views/tweets/_like_button.html.haml
- if current_user.like_tweet?(tweet.id)
  = link_to unlike_tweet_path(tweet), method: :delete, class: 'btn btn-primary btn-sm', remote: true do
    %i.far.fa-thumbs-up
    いいね！
- else
  = link_to like_tweet_path(tweet), method: :post, class: 'btn btn-outline-primary btn-sm', remote: true do
    %i.far.fa-thumbs-up
    いいね！

app/views/tweets/_like_users_modal.html.haml
.modal#like-users-modal{tabindex: '-1', role: 'dialog'}
  .modal-dialog.modal-dialog-centered{role: 'document'}
    .modal-content
      .modal-header
        %h5.modal-title いいね！をしたユーザー
      .modal-body.p-0
        %ul.list-group.list-group-flush
          - tweet.like_users.each do |user|
            %li.list-group-item
              = link_to user.name, user, onclick: "$('.modal').modal('hide');"
      .modal-footer
        %button.btn.btn-secondary{type: 'button', data: {dismiss: 'modal'}} 閉じる

app/views/tweets/_likes_count.html.haml
-# includes(:likes) が効いてない
-# likes_count = tweet.likes.count # SELECT COUNT(*) FROM likes WHERE tweet_id = :id
- likes_count = tweet.likes.pluck(:id).size
- unless likes_count.zero?
  = link_to tweet_likes_path(tweet), remote: true do
    %i.far.fa-thumbs-up
    = likes_count
    いいね！
  %hr/

app/views/tweets/_timeline_content.html.haml
- tweets.each do |tweet|
  .card.mb-3
    .card-body
      %h5.card-title
        .row
          .col-auto.mr-auto= link_to tweet.user.name, tweet.user
          .col-auto
            - if tweet.user == current_user
              = link_to '削除', tweet, method: :delete, class: 'btn btn-sm btn-outline-danger', data: { confirm: '削除してもいいですか？' }
      %p.card-text
        = raw h(tweet.body).gsub(/\R/, '<br>')
        - if tweet.image.present?
          %div
            = link_to tweet.image.url do
              = image_tag tweet.image.thumb.url, class: "img-thumbnail"
      %p.card-text
        %small.text-muted
          = tweet.created_at.strftime('%Y/%m/%d %H:%M')
    .card-footer.border-second.bg-transparent
      .row
        .col{class: "tweet-#{tweet.id}-likes-count"}
          = render partial: 'likes_count', locals: { tweet: tweet }
      .row
        .col.d-flex.justify-content-start
          %div.mr-2{class: "tweet-#{tweet.id}-like"}
            = render partial: 'like_button', locals: { tweet: tweet }
          = link_to tweet_comments_path(tweet), class: 'btn btn-outline-primary btn-sm', remote: true do
            %i.far.fa-comment
            コメント

app/views/tweets/index.html.haml
= link_to '新規投稿画面', new_tweet_path, class: 'btn btn-outline-success mb-2'
%ul.nav.nav-tabs#timeline{role: 'tablist'}
  %li.nav-item
    = link_to '全体タイムライン', '#timeline-all', class: 'nav-link active', id: 'all-tab', data: {toggle: 'tab'}, role: 'tab'
  %li.nav-item
    = link_to 'フォローユーザーのタイムライン', '#timeline-follow-users', class: 'nav-link', id: 'follow-users-tab', data: {toggle: 'tab'}, role: 'tab'
.tab-content#timeline-content.pt-3
  .tab-pane.fade.show.active#timeline-all{role: 'tabpanel'}
    = render partial: 'timeline_content', locals: { tweets: @tweets }
  .tab-pane.fade#timeline-follow-users{role: 'tabpanel'}
    = render partial: 'timeline_content', locals: { tweets: @follow_users_tweets }

#like-users-modal
#comments

app/views/tweets/like.js.erb
$(".tweet-<%= @tweet.id %>-like").html("<%= escape_javascript(render partial: 'like_button', locals: {tweet: @tweet}) %>");
$(".tweet-<%= @tweet.id %>-likes-count").html("<%= escape_javascript(render partial: 'likes_count', locals: {tweet: @tweet}) %>");

app/views/tweets/new.html.haml
%h1 新規投稿
= simple_form_for @tweet do |form|
  = form.error_notification
  = form.input :body, as: :text, label: false
  = form.input :image, as: :file, label: false, input_html: { accept: ".jpg, .jpeg, .png, .gif" }
  = form.button :submit, '投稿する', class: 'btn-outline-primary'
  = link_to '戻る', root_path, class: 'btn btn-outline-secondary'

app/views/tweets/show.js.erb
$("#like-users-modal").replaceWith("<%= escape_javascript(render partial: 'like_users_modal', locals: {tweet: @tweet}) %>");
$("#like-users-modal").modal('show');

app/views/users/show.html.haml
.card.mb-3.mt-3
  .card-header
    .row
      .col-auto.mr-auto ユーザー情報
      .col-auto
        - if current_user != @user
          - if current_user.following?(@user)
            = link_to 'フォロー解除', unfollow_user_path(@user), method: :delete, class: 'btn btn-sm btn-outline-danger'
          - else
            = link_to 'フォローする', follow_user_path(@user), method: :post, class: 'btn btn-sm btn-outline-primary'
  .card-body
    .row
      .col-md-2
        ユーザー名
      .col-md-10
        = @user.name
    %hr/
    .row
      .col-md-2
        プロフィール
      .col-md-10
        = raw h(@user.profile).gsub(/\R/, '<br>')
    %hr/
    .row
      .col-md-2
        ブログURL
      .col-md-10
        = @user.blog_url
= link_to 'トップページへ戻る', root_path, class: 'btn btn-outline-secondary'